#! /bin/sh 

case "$1" in 
      start) 
            cd /home/vagrant 
            /usr/bin/java -jar spring-boot-sample-jetty-1.0.0.RC5.jar & 
            ;; 
      stop) 
            killall -v java 
            ;; 
esac 
exit 0 
